theme: jekyll-theme-minimal

title: "Ryunosuke O'Neil"
description: "Postgraduate Researcher"
logo: "https://avatars1.githubusercontent.com/u/56410978?s=460&u=f045304693e5e5b5bca2f89182a90501a9fcbf44&v=4"

